checks:
    python:
        code_rating: true
        duplicate_code: true

build:
    dependencies:
        override:
            - "pip install -r requirements.txt"
            - "pip install ."
            - "pip install pytest"
    nodes:
        tests:
            tests:
                override: 
                    - command: 'pytest'
                    - py-scrutinizer-run
                    - 
                        command: pylint-run
                        use_website_config: true
filter:
    excluded_paths:
        - '*/docs/*'
        - '*/tests/*'
